//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaNam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string CommentText { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public int ProID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
