//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaNam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProDetail()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProDeID { get; set; }
        public int ProID { get; set; }
        public int SupID { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> OldPrice { get; set; }
        public string Size { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int RemainQuantity { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<int> ViewQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
